### ISSUE TITLE
A parameter cannot be found that matches parameter name 'User'.

### ISSUE THREAD

**Issue by thomas-optimove** [En3Tho/PoshRedisViewer#7]
I need to connect using a redis password.  However when I follow the instructions on the README I get an error about the "User" parameter.

```
PS /xxxxxxxxx> Get-RedisViewer "localhost:6379" -User me -Password myPassword
Get-RedisViewer: A parameter cannot be found that matches parameter name 'User'.
```

I am using MacOs powershell if that effects anything.  If I do not specify the password then I get an authentiction error (so am confident that the ports/firewalls are ok).

I have tried supplying password in the connection string but that results in a timeout on connecting:

```
PS /xxxxxxxxx> Get-RedisViewer "redis://me:mypassword@localhost:6379"
Get-RedisViewer: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
```

Any advice would be appreciated

**Comment by En3Tho** [comment]
Hey. This is simply a bug: it I haven't added Parameter attribute to these properties. Not sure why it doesn't work via connection string though. I guess you've already found something else in these 2 weeks?

**Comment by thomas-optimove** [comment]
> Hey. This is simply a bug: it I haven't added Parameter attribute to these properties. Not sure why it doesn't work via connection string though. I guess you've already found something else in these 2 weeks?

Hi,  thanks for the response.  Its possible I did something wrong with the connection string format.  In the end I moved to other tasks but I anticipate needing to debug the contents of Redis in future so if it is possible to address the bug I would be much appreciated.

**Comment by En3Tho** [comment]
I've updated the module. Please check when you have the time and interest. Also note that this is a very small viewer, it does not support complex stuff like https://redis.io/docs/ui/insight/ for example. So if you really need a feature rich app and not just quick-glance pwsh tool then RedisInsignt would be a better choice for you,

**Comment by thomas-optimove** [comment]
Awesome, thanks.  I have the new package and now am able to supply password and launch app.  But when I press Enter in the KeyQuery box I get the following exception. 

Maybe because I am connecting using IP? Any help would be appreciated <3 

<img width="985" alt="Screenshot 2023-07-25 at 16 49 37" src="https://github.com/En3Tho/PoshRedisViewer/assets/138499004/7dee8502-1b1a-46ed-b50a-7f95b634b321">

**Comment by En3Tho** [comment]
Hmm. Weird. 

It comes from the StackExchange lib. Maybe there is some sort of bug I don't know about? I haven't updated it in a while.

Code is quite straightforward though.

What is your connection string? I believe "localhost:6379" + credentials should work. 

I will look into this again tomorrow. Thank you for your time!

**Comment by En3Tho** [comment]
I belive I've fixed this. I was incorrectly using the api. I don't know if this viewer will be suitable for you in the end but thanks once again.

**Comment by thomas-optimove** [comment]
Working perfectly thanks! Great stuff.  I can see my keys and the contents and the filters working.  This will definetly help with my debugging 🚀
